name: On push to main

on:
  push:
    paths:
      - "start.sh"
      - "Dockerfile"
      - ".github/workflows/release-docker-image.yaml"
    
env:
  HATH_VERSION: 1.6.2
  HATH_CHECKSUM: bb21adeb38e48aeb1892b5cbe603bfeea2c1d653c3d9fafc9e1b336ec0d32dda
  DOCKERHUB_USERNAME: ${{ github.actor }}
  JRE_VERSION: 8u402

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/hath:${{ env.HATH_VERSION }}
            ${{ env.DOCKERHUB_USERNAME }}/hath:${{ env.HATH_VERSION }}-${{ env.JRE_VERSION }}
            ${{ env.DOCKERHUB_USERNAME }}/hath:latest
          build-args: |
            JRE_VERSION=${{ env.JRE_VERSION }}
            HATH_VERSION=${{ env.HATH_VERSION }}
            HATH_CHECKSUM=${{ env.HATH_CHECKSUM }}
